version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5445:5445
    volumes:
      - ./db:/home/postgres/pgdata/data
    env_file:
      - ./.env

volumes:
  postgres:
